defaultSettings:
  defaultReplicaCount: 2
  replicaSoftAntiAffinity: true
  staleReplicaTimeout: 30

  #  Empêche l'auto-création de disques ailleurs
  createDefaultDiskLabeledNodes: false

  #  Chemin UNIQUE du disque Longhorn
  defaultDataPath: /mnt/longhorn

  # Sécurité
  allowNodeDrainWithLastHealthyReplica: false
  disableSchedulingOnCordonedNode: true

ui:
  enabled: true

ingress:
  enabled: true
  host: longhorn.devver.app
  ingressClassName: traefik
  annotations:
    external-dns.alpha.kubernetes.io/target: reverse-proxy.vrhometech.fr
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  tls:
    - hosts:
        - longhorn.devver.app
  secretName: longhorn-tls
  tlsSecret: longhorn-tls

manager:
  enabled: true

#  Longhorn UNIQUEMENT sur les workers
longhornManager:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

longhornDriver:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

longhornUI:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

longhornAdmissionWebhook:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

longhornConversionWebhook:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

longhornRecoveryBackend:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

# ❌ AUCUN disque auto
defaultDiskConfig:
  allowScheduling: false

nodeSelector: {}
tolerations: []
