# Configuration de l'organisation et du projet
organization:
  name: "orgt1"  # Nom de l'organisation
  domain: "devver.app"  # Domaine principal

project:
  name: "projt1"  # Nom du projet
  #displayName: "projtest"  # Nom d'affichage

imagePullSecrets:
  - name: ghcr-secret

# Configuration du conteneur (OS Linux complet ou application)
container:
  image: "ghcr.io/devver-inc/deploy-agent:latest"  # Image du conteneur (OS Linux ou application)
  port: 80  # Port exposé par le conteneur
  type: "app"
  command: []
  args: []

  env:
    DEVVER_SECRET: ""
    NODE_ENV: "production"
    DEVVER_WIDGET_URL: "https://cdn.jsdelivr.net/gh/Devver-Inc/overlay@main/public/devver-overlay.iife.js"
  
# Configuration des ressources
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Configuration de la persistance
persistence:
  enabled: true
  app:
    size: "10Gi"
    mountPath: "/app"
    storageClass: longhorn
  root:
    size: "5Gi"
    mountPath: "/root"
    storageClass: longhorn

# Configuration du nombre de replicas
replicaCount: 1

# Configuration des ports
ports:
  http: 80
  https: 443

# Labels et sélecteurs additionnels
labels: {}
annotations: {}


  