{{- $secretName := printf "%s-keyfile" (include "mongo-template.mongoName" .) }}
{{- $existing := lookup "v1" "Secret" (include "mongo-template.namespace" .) $secretName }}
{{- $replicaSetKey := "" }}
{{- if $existing }}
  {{- $replicaSetKey = index $existing.data "mongodb-keyfile" | b64dec }}
{{- else }}
  {{- $replicaSetKey = randAlphaNum 756 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "mongo-template.namespace" . }}
  labels:
    {{- include "mongo-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-keyfile: {{ $replicaSetKey | quote }}
