apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-template.mongoName" . }}-secret
  namespace: {{ include "mongo-template.namespace" . }}
  labels:
    {{- include "mongo-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Credentials en clair — Vault sera branché ici plus tard sans changer la structure
  MONGO_ROOT_USERNAME: {{ .Values.auth.rootUsername | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  # Connection string reconstruite pour usage par les autres services
  MONGO_CONNECTION_STRING: {{ printf "mongodb://%s:%s@%s:%d/?tls=true&tlsCAFile=/etc/mongo/tls/ca.crt" .Values.auth.rootUsername .Values.auth.rootPassword (include "mongo-template.mongoName" .) (int .Values.port) | quote }}
