apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-template.mongoName" . }}-headless
  namespace: {{ include "mongo-template.namespace" . }}
  labels:
    {{- include "mongo-template.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mongodb
      port: {{ .Values.port }}
      targetPort: mongodb
  selector:
    {{- include "mongo-template.selectorLabels" . | nindent 4 }}
