additionalArguments:
  - "--providers.kubernetesingress=true"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--providers.kubernetescrd=true"
  - "--entrypoints.websecure.address=:8443"
  - "--certificatesresolvers.cloudflare.acme.email=info@devver.app"
  - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns
        key: CF_DNS_API_TOKEN

ports:
  websecure:
    port: 8443        # port interne Traefik
    exposedPort: 443  # port externe pour les clients
    expose:
      default: true

persistence:
  enabled: true
  name: data
  path: /data
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: longhorn

podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: null 
  runAsNonRoot: true

# aucune capability
securityContext: {}

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik
