apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: devver-backend-service
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "kube-system/ghcr-secret"
    reflector.v1.k8s.emberstack.com/reflected-version: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
