apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devver-backend-service
type: Opaque
stringData:
  PORT: "3000"
  NODE_ENV: "production"
  FRONTEND_URL: "https://app.devver.app"
  DATABASE_URL: "mongodb://mongodb.devver-mongodb.svc.cluster.local:27017/"
  DATABASE_NAME: "devver"
  LOGTO_SECRET: "0Dgj70UoGOsl3ep8W5i61zbyGeGB24hQ"
  LOGTO_CLIENT_ID: "4449gm6lla9cqjbzty6md"
  LOGTO_BASE_URL: "https://auth.devver.app"
  LOGTO_WEBHOOK_SIGNING_KEY: "yyTuc6HVM2nnJOXkEe2fuqc4ygG0dAYa"
  STORAGE_ENDPOINT: "http://minio-api-svc.devver-minio.svc.cluster.local:9000"
  STORAGE_ACCESS_KEY: "admin"
  STORAGE_SECRET_KEY: "DevverAdmin1234"
  STORAGE_BUCKET: "devver"
  GITHUB_TOKEN: "secret"
  GITHUB_OWNER: "devver-inc"
  GITHUB_REPO: "argocd-client-deployment"
  GITHUB_BRANCH: "main"
  DEPLOY_AGENT_SECRET: "dev-secret-123"
  K8S_BASE_DOMAIN: "devver.app"
  ENCRYPTION_KEY: "75ffdc4f5c7cc4859a5c61961adfd0f1f532ac25162f07e56050a48f659a45cf"
  ARGOCD_BASE_URL: "https://argocd.devver.app"
  ARGOCD_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJiYWNrZW5kLWFwaTphcGlLZXkiLCJuYmYiOjE3NzQ2MDg2ODEsImlhdCI6MTc3NDYwODY4MSwianRpIjoiZmYyOGEwNzktZjZlYi00MmNkLThmODEtNDhkMTFiNTM4ZGEyIn0.k8bqzdOjj7Zz6blM3Co82GAT1jtXFuN1Kj11Qy9JC9E"
  GIT_TOKEN_SECRET: "bfe87821b9ac3aecdeb322c6ad2ce4466e6fc26cbc295289780f5fbaf6077884"
  GIT_AUTH_URL: "https://app.devver.app/api/v1"
  STORAGE_REGION: "eu-west-2"
  STORAGE_PUBLIC_URL: "minio-api-svc.devver-minio.svc.cluster.local/devver"
  STORAGE_FORCE_PATH_STYLE: "true"
