apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-template.fullname" . }}
  namespace: {{ include "app-template.namespace" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-template.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.project.name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.container.command }}
        command: {{ toJson .Values.container.command }}
        {{- end }}
        {{- if .Values.container.args }}
        args: {{ toJson .Values.container.args }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.container.port }}
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: {{ include "app-template.pvcNameApp" . }}
          mountPath: {{ .Values.persistence.app.mountPath }}
        - name: {{ include "app-template.pvcNameRoot" . }}
          mountPath: {{ .Values.persistence.root.mountPath }}
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: {{ include "app-template.pvcNameApp" . }}
        persistentVolumeClaim:
          claimName: {{ include "app-template.pvcNameApp" . }}
      - name: {{ include "app-template.pvcNameRoot" . }}
        persistentVolumeClaim:
          claimName: {{ include "app-template.pvcNameRoot" . }}
      {{- end }}
