# templates/imagepullsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ include "app-template.namespace" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "kube-system/ghcr-secret"
    reflector.v1.k8s.emberstack.com/reflected-version: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K