apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-template.fullname" . }}
  namespace: {{ include "app-template.namespace" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-template.selectorLabels" . | nindent 4 }}
