apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    # Traefik sait que le service est HTTP
    traefik.ingress.kubernetes.io/service.serversscheme: http
    external-dns.alpha.kubernetes.io/hostname: argocd.k8s.devver.app
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.k8s.devver.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80   # ArgoCD écoute HTTP en interne
  tls:
  - hosts:
      - argocd.k8s.devver.app
    secretName: argocd-tls-public  # secret créé automatiquement par cert-manager
