apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logto-postgres-pvc
  namespace: devver-logto
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi