apiVersion: v1
kind: Namespace
metadata:
  name: etcd-backup
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-details
  namespace: etcd-backup
  labels:
    include: "true"
  annotations:
    kanister.kasten.io/blueprint: "etcd-blueprint"
type: Opaque
stringData:
  cacert: /etc/kubernetes/pki/etcd/ca.crt
  cert: /etc/kubernetes/pki/etcd/server.crt
  endpoints: https://127.0.0.1:2379
  key: /etc/kubernetes/pki/etcd/server.key
  etcdns: kube-system
  labels: component=etcd,tier=control-plane