apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: devver-uptime-kuma
spec:
  storageClassName: nfs-devver-prod
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi