apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kasten-backup-dr
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-backup        # ← même storageClass
  mountOptions:
    - vers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: kasten-backup-dr    # ← nom unique, peu importe
    volumeAttributes:
      server: 192.168.10.5
      share: /volume1/NFS_K8S_DEVVER_BACKUP/pvc-54813501-9114-44e4-b5e2-ab533af98ec8  # ← même share exact que prod
  claimRef:
    namespace: kasten-io
    name: pvc-kasten-backup