apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kasten-backup
  namespace: kasten-io
spec:
  storageClassName: nfs-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-kasten-backup-dr