---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo2
  namespace: np-test
  labels:
    app: nginx-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo2
  template:
    metadata:
      labels:
        app: nginx-demo2
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo2
  namespace: np-test
spec:
  selector:
    app: nginx-demo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo2-ingress
  namespace: np-test
  annotations:
    external-dns.alpha.kubernetes.io/target: reverse-proxy.vrhometech.fr
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
  - host: testnp.k8s.devver.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-demo2
            port:
              number: 80
  tls:
  - hosts:
      - testnp.k8s.devver.app
