apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nfs-devver-prod-snapshot-class
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: nfs.csi.k8s.io
deletionPolicy: Retain
parameters:
  server: "192.168.10.5"
  share: "/volume1/NFS_K8S_DEVVER_PROD"
